print("-"*70)
print("\t\t\tcopying a file")
print("-"*70)
x=input("enter the source file :")
y=input("enter the target file :")
a=open(x,"r")
n=a.read()
b=open(y,"w")
b.write(n)
b.close()
a.close()
print("copied successfully")
print("-"*70)

