print("-"*70)
print("\t\t\tRETAIL BILL SHOP")
print("\t\t*SOAP =30\n\t\t*RICE =50\n\t\t*OIL  =175\n\t\t*BREAD=26\n\t\t*JAM  =20")
print("-"*70)
a=int(input("HOW MUCH SOAP YOU WANT:"))
b=int(input("HOW MUCH RICE YOU WANT:"))
c=int(input("HOW MUCH OIL  YOU WANT:"))
d=int(input("HOW MUCH BREAD YOU WANT:"))
e=int(input("HOW MUCH JAM  YOU WANT:"))
x=(a*30)+(b*50)+(c*175)+(d*26)+(e*20)
print("YOU NEED TO PAY :",x,"ruppees")
print("-"*70)
